graph LR
  subgraph gradle ["Gradle"]
    Transcriber_android_app[Transcriber-android-app]
  end
  subgraph kotlin ["Kotlin"]
    wear[wear]
  end
  subgraph kotlin_cpp ["Kotlin+Cpp"]
    wristlingo[wristlingo]
  end